# Generated by Django 4.2.7 on 2023-12-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
